name: mechanic_calculator
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  cupertino_icons: ^1.0.6
  currency_formatter: ^2.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_sticky_header: ^0.6.5
  gap: ^3.0.1
  shared_preferences: ^2.2.3
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
